version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - AUTH=no
          - MONGODB_URL="mongodb://mongo:27017/"
        volumes:
          - ./data/db:/data/db
        ports: 
            - "27017:27017"
        networks: 
            - all    
    api_backend:
        build:
            context: .
            dockerfile: Dockerfile-backend-api
        ports: 
            - "3001:3001"
        expose:
            - "3001"
        depends_on:
            - mongodb
        links:
            - mongodb
        networks: 
            - all
    api_client:
        build:
            context: .
            dockerfile: Dockerfile-client-api
        ports: 
            - "3000:3000"
        expose:
            - "3000"            
        depends_on:
            - api_backend
        links:
            - api_backend
        networks: 
            - all            
networks:
    all:
