version: '2'
services:
    myapp:
        build: .
        container_name: "api3"
        image: ap3:latest
        ports: 
            - "3001:3001"
        depends_on:
            - mongodb
        networks: 
            - all
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - AUTH=no
          - MONGODB_URL="mongodb://mongo:27017/"
        volumes:
          - ./data/db:/data/db
        ports: 
            - "27017:27017"
        networks: 
            - all
networks:
    all: